name: Build, use Docker Hub deploy MkDocs pages

on:
  workflow_dispatch:
env:
  IMAGE_NAME: ask-me-picturized
  
jobs:
  # Build job
  build:
    name: Build Mkdocs pages and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.2' 

      # mkdocs build
      - name: mkdocs build
        run: |
          pip install -r requirements.txt
          cd readthedocs
          mkdocs build -d _site
      - uses: actions/upload-artifact@v3
        with:
              name: mkdocs-artifact
              path: ${{ github.workspace }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Containerize job to docker hub
  containerize-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: mkdocs-artifact
          path: .
      - name: Log in to the Container registry
        run: docker login  -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
      - name: Deploy image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USER}}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME }}:latest
